spring.application.name=SmartContactManager
server.port=5555

spring.datasource.url=jdbc:mysql://database-1.c7ia04w20tly.ap-south-1.rds.amazonaws.com:3306/smartcontact
spring.datasource.username=admin
spring.datasource.password=RDS_PASSWORD

#spring.datasource.url=jdbc:mysql://localhost:3306/smartcontact
#spring.datasource.username=root
#spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.mvc.view.suffix=.html
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Enable multipart support
spring.servlet.multipart.enabled=true

# Optional limits
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nagasengawai@gmail.com
spring.mail.password=czrs lecj tsvu bmof

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


razorpay.key.id=rzp_test_S0xDK5WMV5khED
razorpay.key.secret=Uy5iWzmBjj3Zktzl3bsVWEL3

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
